[".vim/pack/themes/start/dracula"]
type = "git-repo"
url = "https://github.com/dracula/vim"
refreshPeriod = "720h"
clone.args = ["--depth", "1", "-b", "master"]

[".config/delta/dracula"]
type = "git-repo"
url = "https://github.com/dracula/delta"
refreshPeriod = "720h"
clone.args = ["--depth", "1", "-b", "main"]

[".tmux/plugins/dracula"]
type = "git-repo"
url = "https://github.com/dracula/tmux"
refreshPeriod = "720h"
clone.args = ["--depth", "1", "-b", "master"]

[".config/dircolors/dracula"]
type = "git-repo"
url = "https://github.com/dracula/dircolors"
refreshPeriod = "720h"
clone.args = ["--depth", "1", "-b", "main"]
